"""empty message

Revision ID: 96575d96e62e
Revises: 247682eede2a
Create Date: 2023-04-01 20:33:11.710556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96575d96e62e'
down_revision = '247682eede2a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
